// @ts-check
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';
import remarkMath from 'remark-math';
import remarkDirective from 'remark-directive';
import rehypeKatex from 'rehype-katex';
import remarkPractice from './src/lib/markdown/remark-practice.mjs';
import rehypeCleanHeadingMath from './src/lib/markdown/rehype-clean-heading-math.mjs';
import redirects from './src/redirects.json' with { type: 'json' };
import notesSidebar from './src/sidebar.json' with { type: 'json' };

// Make every sidebar group collapsed by default. Starlight always auto-expands
// the group(s) containing the current page, so this gives proper accordion
// behaviour: only the current course/unit is open, instead of every group being
// rendered expanded (which made navigation appear to "auto-open" big groups like
// AP Calculus on each page load).
const collapseGroups = (items) =>
	items.map((it) => (it.items ? { ...it, collapsed: true, items: collapseGroups(it.items) } : it));

// https://astro.build/config
export default defineConfig({
	// Primary site is GitHub Pages at the existing domain.
	site: 'https://notesbyjoshua.github.io',
	// Pre-bundle the Supabase SDK so the dev server doesn't re-optimize it
	// mid-session (the cause of "504 Outdated Optimize Dep").
	vite: {
		optimizeDeps: { include: ['@supabase/supabase-js'] },
	},
	// Preserve old URLs from reorganized notes (generated by scripts/migrate_notes.py).
	redirects,
	markdown: {
		// MathJax-style `$...$` (inline) and `$$...$$` (display) delimiters, rendered with KaTeX.
		// remarkDirective parses `:::name{...}` blocks; remarkPractice turns
		// `:::problem` / `:::frq{id=…}` / `:::solution` into the practice-box markup
		// the grader + reveal toggles hook into (other directives are left alone).
		remarkPlugins: [remarkMath, remarkDirective, remarkPractice],
		// strict: false -> render quirks like an em-dash inside math instead of warning.
		// rehypeCleanHeadingMath runs AFTER katex to de-duplicate heading text so the
		// "On this page" ToC isn't garbled (e.g. "KcK_cKc"); body math is untouched.
		rehypePlugins: [[rehypeKatex, { strict: false }], rehypeCleanHeadingMath],
	},
	integrations: [
		starlight({
			title: 'Notes by Joshua',
			description: 'Math, Physics, and Thoughts',
			// Show "Last updated" (from git history) in the page footer.
			lastUpdated: true,
			favicon: '/assets/Images/favicon.jpeg',
			components: {
				// Show an account indicator in the header (keeps social icons too).
				SocialIcons: './src/components/HeaderAccount.astro',
				// Add a Bookmark toggle next to the title on note pages.
				PageTitle: './src/components/PageTitle.astro',
				// Add a "Report an issue with this note" link in the page footer.
				Footer: './src/components/Footer.astro',
			},
			social: [{ icon: 'github', label: 'GitHub', href: 'https://github.com/notesbyjoshua' }],
			customCss: [
				// KaTeX stylesheet (math rendering).
				'katex/dist/katex.min.css',
				// Inter font + theorem boxes + note images, ported from the Jekyll site.
				'./src/styles/custom.css',
			],
			head: [
				{
					tag: 'link',
					attrs: { rel: 'preconnect', href: 'https://fonts.googleapis.com' },
				},
				{
					tag: 'link',
					attrs: { rel: 'preconnect', href: 'https://fonts.gstatic.com', crossorigin: true },
				},
				{
					tag: 'link',
					attrs: {
						rel: 'stylesheet',
						href: 'https://fonts.googleapis.com/css2?family=Inter:wght@400;600&display=swap',
					},
				},
				// Google Analytics (same measurement ID as the old site).
				{
					tag: 'script',
					attrs: { async: true, src: 'https://www.googletagmanager.com/gtag/js?id=G-868QCS9DJP' },
				},
				{
					tag: 'script',
					content:
						"window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments);}gtag('js',new Date());gtag('config','G-868QCS9DJP');",
				},
				// Neutralise Starlight's sidebar-state persister (it remembers which
				// groups you opened in sessionStorage and re-opens them on the next
				// page — so a manually-opened group like AP Calculus would reappear on
				// unrelated pages). Clearing the key in <head>, before the body's
				// restore script runs, makes every page use its correct server-rendered
				// accordion state (only the current page's group open). Runs head-first.
				{
					tag: 'script',
					content: "try{sessionStorage.removeItem('sl-sidebar-state')}catch(e){}",
				},
				// Sidebar accordion: opening a nav group collapses its open siblings so
				// the sidebar stays tidy. `toggle` doesn't bubble, but a capture-phase
				// listener still sees it, so one delegated handler covers every group.
				{
					tag: 'script',
					content:
						"document.addEventListener('toggle',function(e){var d=e.target;if(!(d instanceof HTMLDetailsElement)||!d.open||!d.closest('ul.top-level'))return;var li=d.closest('li'),ul=li&&li.parentElement;if(!ul)return;ul.querySelectorAll(':scope > li > details[open]').forEach(function(o){if(o!==d)o.open=false;});},true);",
				},
				// Social-share image (Starlight already emits og:title/description + canonical).
				// 1200x630 card generated by scripts/build-og-card.mjs; large card so it
				// renders as a full-width preview in Discord/iMessage/Twitter.
				{ tag: 'meta', attrs: { property: 'og:image', content: 'https://notesbyjoshua.github.io/assets/Images/og-card.png' } },
				{ tag: 'meta', attrs: { property: 'og:image:width', content: '1200' } },
				{ tag: 'meta', attrs: { property: 'og:image:height', content: '630' } },
				{ tag: 'meta', attrs: { name: 'twitter:image', content: 'https://notesbyjoshua.github.io/assets/Images/og-card.png' } },
				{ tag: 'meta', attrs: { name: 'twitter:card', content: 'summary_large_image' } },
			],
			sidebar: [
				{ label: 'Home', link: '/' },
				{ label: 'How to use these notes', link: '/how-to-use-these-notes/' },
				// Built from parent/nav_order by scripts/migrate_notes.py (src/sidebar.json),
				// so units group under their real course regardless of URL folder.
				{ label: 'Notes', collapsed: true, items: collapseGroups(notesSidebar) },
				// Per-course practice pages are generated by scripts/build_practice.py;
				// autogenerate picks up the overview + each course page automatically.
				{ label: 'Practice Problems', collapsed: true, items: [{ autogenerate: { directory: 'practiceproblems', collapsed: true } }] },
				{ label: 'Resources', link: '/resources/resources/' },
				{ label: 'Blog', link: '/blog/' },
				{ label: 'About', link: '/about/' },
				{ label: 'Feedback', link: '/feedback/' },
				{ label: 'My Dashboard', link: '/dashboard/' },
				{ label: 'Account', link: '/account/' },
			],
		}),
	],
});
